version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.9.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
     # Endereço do Zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1

    # 1. Define os listeners que o Kafka deve escutar:
    #   INTERNAL: para comunicação dentro do Docker (entre brokers/serviços)
    #   EXTERNAL: para comunicação de fora do Docker (seu Spring Boot)
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092

    # 2. Define como o Kafka deve se anunciar para o mundo (muito importante!):
    #   INTERNAL: Se anuncia como 'kafka:29092' (para o Zookeeper e outros containers)
    #   EXTERNAL: Se anuncia como 'localhost:9092' (para o Spring Boot na sua máquina)
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

    # 3. Mapeamento de protocolo de segurança:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

    # 4. Listener usado para comunicação inter-broker (usamos o interno)
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    container_name: mysql-stock
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w
      MYSQL_DATABASE: stock_db # Apenas um BD
    command: --default-authentication-plugin=mysql_native_password